/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LL_H_RPCGEN
#define _LL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct foo {
	int x;
	struct foo *next;
};
typedef struct foo foo;

struct tree {
	int x;
	struct tree *left;
	struct tree *right;
};
typedef struct tree tree;

#define LL_PROG 0x20000210
#define LL_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define in 1
extern  tree * in_1(foo *, CLIENT *);
extern  tree * in_1_svc(foo *, struct svc_req *);
extern int ll_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define in 1
extern  tree * in_1();
extern  tree * in_1_svc();
extern int ll_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_foo (XDR *, foo*);
extern  bool_t xdr_tree (XDR *, tree*);

#else /* K&R C */
extern bool_t xdr_foo ();
extern bool_t xdr_tree ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LL_H_RPCGEN */
