/*
 * This is sample code generated by rpcgen.


 * These are only templates and you can use them

 
* as a guideline for developing your own functions.
 */




#include <stdio.h>


#include <stdlib.h>


#include "ll.h"




tree*bst(foo *argp);
/* remote procedure that sums the ints in the linked list */
 


tree *in_1_svc(foo *argp, struct svc_req *rqstp)

{

	
	tree*result;

	result=bst(argp);

	return result;

}


tree*bst(foo *argp)
{

	tree*temp,*list,*root;

	root=NULL;

	while(1)

	{

		temp=(tree*)malloc(sizeof(tree));

		temp->x=argp->x;

		temp->left=NULL;

		temp->right=NULL;

		if(root==NULL)

		{

			root=temp;

			list=temp;

		}

		else

		{

			list=root;

			while(1)

			{

				if(list->x==argp->x)

				{

					printf("data already present");

					break;

				}

				else if((argp->x<list->x)&&(list->left!=NULL))

				list=list->left;

				else if((argp->x>list->x)&&(list->right!=NULL))

				list=list->right;

				else if((argp->x<list->x)&&(list->left==NULL))

				{

					list->left=temp;

					break;

				}

				else if((argp->x>list->x)&&(list->right==NULL))

				{

					list->right=temp;

					break;

				}

			}

		}

		if(argp->next==NULL)

		break;


		else

		argp=argp->next;

	}

	return root;

}
